# Generated by Django 5.0.2 on 2024-02-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=200)),
                ('reply', models.BooleanField(default=True)),
                ('date', models.DateTimeField(verbose_name='delivery date')),
                ('message_sender', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.sender')),
            ],
        ),
    ]
